permalink: /:year/:month/:title/
url: http://yikebocai.com
author: yikebocai
pygments: true
paginate: 20
markdown: redcarpet
redcarpet:
  extensions: ["tables","no_intra_emphasis", "fenced_code_blocks", "autolink",  "with_toc_data"]
