permalink: /:year/:month/:title/
url: http://xinbo.me
author: yikebocai
timezone: Asia/Shanghai
paginate: 20
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]

