permalink: /:year/:month/:title/
url: http://yikebocai.com
author: yikebocai
pygments: true
paginate: 24
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
