permalink: /:year/:month/:title/
url: http://yikebocai.com
author: yikebocai
pygments: true
paginate: 20
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
